### ISSUE TITLE
point landsat.club to our EC2 box

### ISSUE THREAD

**Issue by jacquestardie** [recombinators/landsat#13]
Not sure how to do this without having access to the AWS console otherwise I would. At some point, think we'll have to work with [Route53](https://aws.amazon.com/route53/)

**Comment by constanthatz** [comment]
Send me the zone file from the gandi.net and I will set up Route 53 (https://wiki.gandi.net/en/dns)

**Comment by constanthatz** [comment]
I think I am also going to need access to gandit.net

**Comment by jacquestardie** [comment]
no
